src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $billets;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }
    
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getBillets(): ?string
    {
        return $this->billets;
    }

    public function setBillets(string $billets): self
    {
        $this->billets = $billets;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }
}

templates/programme/ActivitesAnimations.html.twig
{% extends 'base.html.twig' %}

{% block title %} Activité-Animations {% endblock %}

{% block body %}

<div class="container border-light">

    <h2> Activité & Animations :  </h2>

    <div class="container">

        <div class="card" style="width: 18rem;">
            <a href="/ConcoursCosplay"> <img src="assets/img/animation.jpg" class="card-img-top" alt="animation"> </a>
            <div class="card-body">
                <p class="card-text">Concours cosplay</p>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="card" style="width: 18rem;">
            <a href="/Karaoke"> <img src="assets/img/karaoke1.jpg" class="card-img-top" alt="animation"> </a>
            <div class="card-body">
                <p class="card-text">Karaoke</p>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="card" style="width: 18rem;">
        <a href="/Quizz"> <img src="assets/img/quizz.jpg" class="card-img-top" alt="animation"></a>
            <div class="card-body">
                <p class="card-text">Quizz mangas</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/programme/AntoineDaniel.html.twig
{% extends 'base.html.twig' %}

{% block title %} Antoine Daniel {% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Antoine Daniel</h1>
    <p class="lead">
        <img class="d-block" src="assets/img/antoineDan.jpg" style="width : 30%"> 
    </p>
    <p class="lead">
       
       « En fait je voulais juste appeler le compte AntoineDaniel à la base puisque je m'appelle comme ça,
        mais un pauvre type l'a déjà pris avant. Je le déteste. Du coup j'ai mis Mr avant. C'est comme si 
        j'avais un chapeau haut de forme﻿ sur la tête. Cool story bro. » - Antoine Daniel. 
    </p>

    <p class="lead">

        Ce youtubeur hors du commun sera présent à notre convention le Samedi. Il est notamment connu pour ses vidéos
        "What the cut" sur sa chaine youtube MrAntoineDaniel.
        Les dédicaces se dérouleront entre 14h et 16h. 
    </p>
  </div>
</div>

{% endblock %}

templates/programme/ConcoursCosplay.html.twig
{% extends 'base.html.twig' %}

{% block title %} Activité-Animations {% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <br>
    <h1 class="display-4">Concours cosplay</h1>
    <p class="lead">
        Organisé et animé par notre formidable équipe,
        ce concours a pour but de mettre en valeur votre travail et votre univers.
    </p>
    <p class="lead">
        Ce Samedi de 17h à 18h, Le Concours Cosplay :

        Il sera précédé d’un rendez-vous afin de faire connaissance, venir chercher ou donner quelques conseils. Les prix pour ce
        concours seront plus que symboliques, juste pour le fun et si les 3 premiers auront un cadeau supplémentaire tous les participants
        repartiront avec un souvenir de ce moment. 
    </p>
    <p class="lead">
        Vous pouvez consulter le règlement ci-dessous et vous inscrire en téléchargeant le formulaire
        d'inscription ci-dessus à rendre dés le matin à l'accueil de la convention.
    </p>
      <br>
        <br>
        <img class="d-block center_img" src="assets/img/GroupCosplay.jpg" alt="First slide" style="width : 50%"> 
          <br>
            <br>
  </div>
</div>

{% endblock %}

templates/programme/Cosplayers.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Reika</h1>
    <p class="lead">
        <img class="d-block" src="assets/img/reika_cos.jpg" style="width : 30%"> 
    </p>
    <p class="lead">
       
       REIKA est une cosplayeuse japonaise de renom qui nous vient d’Osaka. Elle est invitée dans des conventions et événements
    partout dans le monde, en Asie, en Europe, aux États-Unis et en Amérique du Sud.
     Elle pratique le cosplay depuis 20 ans, et a plus de 500 costumes à son actif. Elle anime également des ateliers sur la
    pose de perruques, le maquillage et la fabrication de costumes. 
    </p>

    <p class="lead">
        Cette cosplayeuse mondialement connue sera présent à notre convention le Samedi.
        Les dédicaces se dérouleront entre 15h et 17h. 
    </p>
  </div>
</div>

{% endblock %}

templates/programme/Exposants.html.twig
{% extends 'base.html.twig' %}

{% block title %} Exposants {% endblock %}

{% block body %}

<div class="container">
    <h2> Les exposants :   </h2>


     <table class="table">
        <thead>
            <tr style="text-align:center">
                <th>Nom</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.nom }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Aucun exposant</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/programme/Invites.html.twig
{% extends 'base.html.twig' %}

{% block title %} Invités {% endblock %}
{% block stylesheets %} <link href="/assets/css/style.css" rel="stylesheet"> {% endblock %}

{% block body %}

<div class="container border">
  <h2> Les invités :  </h2>
  <p>Mangaka, professionnels de l’animation, chara-designers, illustrateurs, créateurs de jeux vidéo, producteurs, musiciens, chanteurs, compositeurs… : ces invités sont nombreux à faire le voyage depuis le Japon pour venir assister au festival.

  Ne manquez pas la chance de rencontrer ces artistes talentueux, d'assister à des shows exceptionnels et d’en apprendre plus sur nos invités.</p>
</div>

<div>
<br>
  <h3> Mangaka & Animations :  </h3>
    <div class="container_invites">
      <a href="/KillingStalking">  <img class="d-block" src="assets/img/killingstalking.jpg" alt="First slide"> </a>
    </div>
</div>

<div>
<br>
  <h3> Cosplayers :  </h3>
    <div class="container_invites">
      <a href="/Cosplayers"> <img class="d-block" src="assets/img/reika_2.jpg" alt="First slide"> </a>
    </div>
</div>

<div>
  <h3> Youtubeurs :  </h3>
    <div class="container_invitess">
        <a href="/AntoineDaniel"> <img class="youtubeur" src="assets/img/daniel.jpg" alt="First slide"> </a>
        <a href="/RireJaune"> <img class="youtubeur" src="assets/img/rire.jpg" alt="First slide"> </a>
        <a href="/LeGrandJD"><img class="youtubeur" src="assets/img/grand.jpg" alt="First slide"> </a>
        <a href="/JDG"><img class="youtubeur" src="assets/img/joueur_grenier.jpg" alt="First slide"> </a>
    </div>
</div>
{% endblock %}

templates/programme/JDG.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Le joueur du grenier</h1>
    <p class="lead">
        <img class="d-block" src="assets/img/JDG2.jpg" style="width : 50%"> 
    </p>

    <p class="lead">

        Ce youtubeur incontournable sera présent à notre convention le Samedi. Sur ses chaines Joueur du Grenier et Bazar du Grenier, il anime plusieurs émissions sur le thème des jeux-videos. Son humour lui a valu d'être rapidemment connu. C'est désormais une référence en terme de vidéos sur le rétro-gamming.
        Les dédicaces se dérouleront entre 14h et 16h. 
    </p>
  </div>
</div>

{% endblock %}

templates/programme/Karaoke.html.twig
{% extends 'base.html.twig' %}

{% block title %} Activité-Animations {% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
        <br>
    <h1 class="display-4">Karaoke</h1>
    <p class="lead">
        Peu importe votre talent, venez pousser la chansonnette sur la grand scène et participer aux sessions karaoke 
        organisées par l’association Bel'Op ! Des quizz et des blindtests sont également prévus, pour plus d'amusement !
    </p>
          <br>
        <br>
        <img class="d-block center_img"" src="assets/img/Karaoke2.jpg" alt="First slide" style="width : 55%"> 
          <br>
            <br>
  </div>
</div>

{% endblock %}

templates/programme/KillingStalking.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Killing Stalking</h1>
    

    <img class="d-block" src="assets/img/KS.jpg" style="width : 20%"> 
    

     <p class="lead">

       Koogi est une manhwaga qui vient de débuter sa carrière avec le webcomic Killing Stalking. Ce dernier est publié par Lezhin et pré-publié dans le magazine Lezhin.
    </p>

    <p class="lead">

       Un jeune homme nommé Yoonbum est fou amoureux du garçon le plus populaire de son université, Sangwoo, malgré le fait qu'il sache mieux que personne qu'il ne sera jamais à ses cotés. Son amour à sens unique l'entraîne à s'introduire dans la maison de ce dernier, mais ce qu'il découvre là-bas va complètement bouleverser sa vie...
       Les dédicaces se dérouleront entre 14h et 16h. 
    </p>
  </div>
</div>

{% endblock %}

templates/programme/LeGrandJD.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Le Grand JD</h1>
    <p class="lead">
        <img class="d-block" src="assets/img/Grand-JD2.jpg" style="width : 30%"> 
    </p>

    <p class="lead">

        Le grand JD est un vidéaste  éclectique qui expérimente de nombreux formats parmi lesquels nous retrouvons des vidéos parodiques (films, pubs, jeux vidéos, etc.) mais également des clips musicaux à la composition pour le moins originale. Il se passionne également pour l’Urbex et l’étrange, thèmes autour desquels il réalise de nombreuses autres vidéos à caractère plus documentaire.
        Les dédicaces se dérouleront entre 14h et 16h. 
    </p>
  </div>
</div>

{% endblock %}

templates/programme/Quizz.html.twig
{% extends 'base.html.twig' %}

{% block title %} Activité-Animations {% endblock %}

{% block body %}


<div class="jumbotron jumbotron-fluid">
  <div class="container">
        <br>
    <h1 class="display-4">Quizz</h1>
    <p class="lead">
        Pour la première fois, nous vous donnons rendez-vous sur la scène principale le samedi à 13h30 et le dimanche à
        14h30 pour vous offrir des tonnes de cadeaux ! Des DVD, des manga, des goodies en tout genre que les geeks les plus rapides 
        vont s’arracher! 
    </p>
    <p class="lead">
        Rejoignez notre équipe déjantée pour ce Quizz et tentez de gagner des dizaines de cadeaux !
    </p>
          <br>
        <br>
        <img class="d-block center_img" src="assets/img/MyQuizz2.png" alt="Quizz" style="width : 50%"> 
          <br>
            <br>
  </div>
</div>

{% endblock %}

templates/programme/RireJaune.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Le Rire Jaune</h1>
    <p class="lead">
        <img class="d-block" src="assets/img/RireJaune2.jpg" style="width : 30%"> 
    </p>

    <p class="lead">

        Le Rire Jaune est un duo de vidéastes web français, composé de deux frères, Kevin Kē Wěi Tran et Henry Kē Liáng Tran. Ils publient leurs vidéos sur la plateforme YouTube sur leur chainee LeRireJaune.
        Les dédicaces se dérouleront entre 13h et 15h.
    </p>
  </div>
</div>

{% endblock %}